# Generated by Django 3.1.2 on 2020-10-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_path',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
